<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getByDate(\Datetime $date1, \Datetime $date2)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->where('a.date BETWEEN :date1 AND :date2')
            ->setParameter('date1', $date1->format('Y-m-d'))
            ->setParameter('date2', $date2->format('Y-m-d'));
        
        $query = $queryBuilder->getQuery();
        
        return $query->getResult();
    }

    public function getAvecTags(array $tags)
    {
        $qb = $this->createQueryBuilder('a');

        // On fait une jointure sur la table des tags, avec pour alias 't'
        $qb ->join('a.tags', 't')
            ->where($qb->expr()->in('t.nom', $tags)); // Puis on filtre sur le nom des tags

        // enfin, on retourne le résultat
        return $qb->getQuery()->getResult();
    }
}